version: "3"

services:

  gradio_v1:
    build: .
    runtime: nvidia
    container_name: gradio_yolov7
    restart: always
    volumes:
      - .:/gradio
    tty: true
    ports:
      - "9999:9999"
    command: python main.py
